### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by artisticcheese** [rcarmo/azure-docker-swarm-cluster#6]
Looking to implement similar setup with Windows containers and wondering how VMSS are joining/leaving swarm automatically. I don't see it anywhere in template location for the script which performs this functino and how it's being done.

**Comment by rcarmo** [comment]
That’s done as part of the CustomData that is passed on to cloud-init on Linux. I set up a set of small services to do that in the .yml files.

**Comment by artisticcheese** [comment]
What is "cloud-init". Is it some sort of script which runs when OS boots up? I'm looking in high level algorithm without specifics what is being done on worker nodes to make them join swarm and more importantly what is being done swarm managers to keep swarm clean in situations where VMSS are scaled up or down

**Comment by rcarmo** [comment]
Cloud-init is a Linux standard for cloud instance configuration:

https://cloud-init.io

If you look through the files in the cloud-config folder, they contain the scripts used for worker nodes to join/leave the swarm, which are actually quite simple. Also, the Channel 9 video has a short explanation of the process, but in short I set up a minimal web server on the masters that is notified when a node is added/removed from the VMSS.

**Comment by artisticcheese** [comment]
Are you subscribed to some sort of Azure event when VMSS is changed or how
web server knows about changes to VMSS

**Comment by rcarmo** [comment]
No, the ACPI shutdown notification is enough for the node to remove itself from the cluster.

See https://github.com/rcarmo/azure-docker-swarm-cluster/blob/master/cloud-config/agent.yml#L39

I have a timer that checks node status in the master:

https://github.com/rcarmo/azure-docker-swarm-cluster/blob/master/cloud-config/master.yml#L42

…but in practice the nodes shut down in an orderly fashion, so it was hardly necessary.

Doing the same on Windows is non-trivial (or will at least require a lot more effort and some custom code), but ACS includes that functionality in the Windows variants (or at least so I’m told).

**Comment by artisticcheese** [comment]
Well it's not a problem to subscribe to shutdown event in Windows. What I don't understand is why do you want to remove node from cluster on shutdown, there might be legitimate reasons to shutdown/reboot node without necessity of removing it from cluster.

**Comment by rcarmo** [comment]
Well, largely because I don’t redeploy nodes - I prefer to have completely fresh machines, if possible re-imaged from the exact same base image.

Also, if you read the scripts (and the README), nodes remove themselves upon reboot as well, to let the cluster know beforehand that it will have to drain and reschedule container loads elsewhere.
