### ISSUE TITLE
SSL Offloading

### ISSUE THREAD

**Issue by justin-vanwinkle** [rcarmo/azure-docker-swarm-cluster#7]
Thanks for sharing your work, it is very helpful!

In our particular scenario, we would like to do SSL offloading at the load balancer so that each of the agents doesn't have to be given the SSL certificate and a corresponding password.  

Since the Azure Load Balancer doesn't support SSL offloading, I'm curious if there are any known drawbacks to using the Azure Application Gateway instead?

**Comment by rcarmo** [comment]
Hey there!

Glad to be of help! I use this template a lot myself, actually, and will eventually add a few more tweaks.

I haven’t used the WAF yet myself in depth (I have played around with it and helped customers out with it, but haven’t actually dug in and tested it to smithereens), but it should work fine, although it will be a bit weird to point it at the scaleset without using the load balancer (which is kept in sync with instance counts).

Incidentally, Swarm’s built in load balancing is still a bit iffy. When using containers only, I tend to use traefik instead for load balancing and SSL termination, and stick the load balancer in front of a couple of instances, but container networking and HA are still not perfect partners...

**Comment by justin-vanwinkle** [comment]
Thanks for providing some direction here.

For our initial attempts, we decided to go with a single Application Gateway in front of a Load Balancer that points to the VM Scale Set.  The AG does path-based routing to ports for each of the applications that run on the agents (similar to what Traefik can do).

I will leave this open for now and report back with what we put in production.

**Comment by rcarmo** [comment]
Awesome!

**Comment by justin-vanwinkle** [comment]
Thanks for holding this open.  We experienced a lot of trouble with Docker Swarm and decided to opt for something else in its place.  Thanks for your help along the way!
